---
title: Daniel Torquato
description: Research & Development Engineer

jupyter: python3
---

> Senior Full-Stack Engineer & Data Scientist

::: {.grid .d-block .d-md-grid}

::: {.g-col-12 .g-col-md-8}

### Overview

Research & Development Engineer with experience in software development, data science, and machine learning. As a Senior Full-Stack Engineer, I integrate Front-End and Back-End technologies to develop innovative and efficient solutions. Passionate about data-driven insights and AI, I continuously seek to enhance systems through research, optimization, and cutting-edge technology.

---

### Experience

```{python}
from widgets import loadResume, renderEducation, renderExperience

resume = loadResume("data/resume.yml")
```

```{python}
renderExperience(resume)
```

:::

::: {.g-col-12  .g-col-md-4}

::: {.d-block .d-md-none}

---

:::

### Education

```{python}
renderEducation(resume)
```

##### And more: [Licenses and certificates](https://www.linkedin.com/in/danieltorquatof/details/certifications/){target="_blank"}

##### See also my [Skills](https://www.linkedin.com/in/danieltorquatof/details/skills/){target="_blank"}

---

### Main Languages

::: {.grid}

::: {.column}
- Python
- Julia
- R
- Dart
- C#
- PHP
- SQL
:::

::: {.column}
- NoSQL
- Kotlin
- Java
- JavaScript
- TypeScript
- HTML
- CSS
:::

:::

---

### Some Frameworks and Technologies

::: {.grid}

::: {.column}
- AWS
- Flutter
- React
- React Native
- Express.js
- CodeIgniter
- FastAPI
- ASP.NET
:::

::: {.column}
- MySQL
- MariaDB
- MongoDB
- Node.js
- Shiny
- Oxygen.jl
- Jupyter
:::

:::

---

### Game Engines

::: {.grid}

::: {.column}

- Unity
- Godot

:::

:::

:::

:::
